name: Deploy Hexo Blog
on: 
  push:
    branches:
      - main

jobs:
  GZ-server:
    name: Test Hexo Blog
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v6.0.2
      
      - name: 查看目录
        run: ls -lha


        