name: Deploy Hexo Blog
on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Test Hexo Blog
    runs-on: ubuntu-latest

    steps:
      - name: hello hexo
        run: echo "hello hexo"
      - name: 查看目录
        run: pwd
