name: Deploy Hexo Blog To Dev
on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Hexo Blog
    runs-on: ubuntu-latest

    steps:
      - name: Update Hexo Blog To Master
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GZ_DEV_SERVER_HOST }}
          username: ${{ secrets.GZ_SERVER_USERNAME }}
          key: ${{ secrets.GZ_SERVER_KEY }}
          script: |
            cd /opt/Cloud-Compute-WikiData
            git pull origin dev
            ls -la