name: Deploy Hexo Blog To Master
on: 
  push:
    branches:
      - main

jobs:
  GZ-server:
    name: Deploy Hexo Blog
    runs-on: ubuntu-latest

    steps:
      - name: Update Hexo Blog To Master
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GZ_SERVER_HOST }}
          username: ${{ secrets.GZ_SERVER_USERNAME }}
          key: ${{ secrets.GZ_SERVER_KEY }}
          script: |
            cd /opt/cloud-compute-wiki-data
            git pull origin main
            ls -la
            /root/.nvm/versions/node/v26.2.0/bin/node /root/.nvm/versions/node/v26.2.0/bin/hexo clean
            systemctl restart hexo.service


        
